"""Initial migration

Revision ID: 217fbf37bd5e
Revises: 
Create Date: 2025-02-11 21:39:36.989693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217fbf37bd5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('forget_password_token', sa.String(), nullable=True),
    sa.Column('forget_password_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forget_password_token_used', sa.Boolean(), nullable=True),
    sa.Column('verify_user_token', sa.String(), nullable=True),
    sa.Column('verify_user_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verify_user_token_used', sa.Boolean(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('business_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
