"""Updated models to use Mapped and mapped_column

Revision ID: 5b425b6bbe0c
Revises: 7ca78961f7d1
Create Date: 2025-02-14 10:20:15.601007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b425b6bbe0c'
down_revision: Union[str, None] = '7ca78961f7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'forget_password_token_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'verify_user_token_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'verify_user_token_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'forget_password_token_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
